apiVersion: v1
kind: Service
metadata:
  name: adjiamaguette-ndiaye
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: adjiamaguette-ndiaye
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: ClusterIP
